# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from etsy_python_sdk.models.shop import Shop

class TestShop(unittest.TestCase):
    """Shop unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Shop:
        """Test Shop
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Shop`
        """
        model = Shop()
        if include_optional:
            return Shop(
                shop_id = 1,
                user_id = 1,
                shop_name = '',
                create_date = 0,
                created_timestamp = 0,
                title = '',
                announcement = '',
                currency_code = '',
                is_vacation = True,
                vacation_message = '',
                sale_message = '',
                digital_sale_message = '',
                update_date = 0,
                updated_timestamp = 0,
                listing_active_count = 0,
                digital_listing_count = 0,
                login_name = '',
                accepts_custom_requests = True,
                policy_welcome = '',
                policy_payment = '',
                policy_shipping = '',
                policy_refunds = '',
                policy_additional = '',
                policy_seller_info = '',
                policy_update_date = 0,
                policy_has_private_receipt_info = True,
                has_unstructured_policies = True,
                policy_privacy = '',
                vacation_autoreply = '',
                url = '',
                image_url_760x100 = '',
                num_favorers = 0,
                languages = [
                    ''
                    ],
                icon_url_fullxfull = '',
                is_using_structured_policies = True,
                has_onboarded_structured_policies = True,
                include_dispute_form_link = True,
                is_direct_checkout_onboarded = True,
                is_etsy_payments_onboarded = True,
                is_calculated_eligible = True,
                is_opted_in_to_buyer_promise = True,
                is_shop_us_based = True,
                transaction_sold_count = 0,
                shipping_from_country_iso = '',
                shop_location_country_iso = '',
                review_count = 56,
                review_average = 1.337
            )
        else:
            return Shop(
        )
        """

    def testShop(self):
        """Test Shop"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
