# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from etsy_python_sdk.models.shop_receipt import ShopReceipt

class TestShopReceipt(unittest.TestCase):
    """ShopReceipt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShopReceipt:
        """Test ShopReceipt
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShopReceipt`
        """
        model = ShopReceipt()
        if include_optional:
            return ShopReceipt(
                receipt_id = 1,
                receipt_type = 0,
                seller_user_id = 1,
                seller_email = '',
                buyer_user_id = 1,
                buyer_email = '',
                name = '',
                first_line = '',
                second_line = '',
                city = '',
                state = '',
                zip = '',
                status = 'paid',
                formatted_address = '',
                country_iso = '',
                payment_method = '',
                payment_email = '',
                message_from_seller = '',
                message_from_buyer = '',
                message_from_payment = '',
                is_paid = True,
                is_shipped = True,
                create_timestamp = 946684800,
                created_timestamp = 946684800,
                update_timestamp = 946684800,
                updated_timestamp = 946684800,
                is_gift = True,
                gift_message = '',
                gift_sender = '',
                grandtotal = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                subtotal = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                total_price = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                total_shipping_cost = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                total_tax_cost = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                total_vat_cost = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                discount_amt = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                gift_wrap_price = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                shipments = [
                    null
                    ],
                transactions = [
                    null
                    ],
                refunds = [
                    null
                    ]
            )
        else:
            return ShopReceipt(
        )
        """

    def testShopReceipt(self):
        """Test ShopReceipt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
