# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from etsy_python_sdk.models.shop_shipping_profile_destination import ShopShippingProfileDestination

class TestShopShippingProfileDestination(unittest.TestCase):
    """ShopShippingProfileDestination unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ShopShippingProfileDestination:
        """Test ShopShippingProfileDestination
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ShopShippingProfileDestination`
        """
        model = ShopShippingProfileDestination()
        if include_optional:
            return ShopShippingProfileDestination(
                shipping_profile_destination_id = 1,
                shipping_profile_id = 1,
                origin_country_iso = '',
                destination_country_iso = '',
                destination_region = 'eu',
                primary_cost = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                secondary_cost = etsy_python_sdk.models.money.Money(
                    amount = 56, 
                    divisor = 0, 
                    currency_code = '', ),
                shipping_carrier_id = 56,
                mail_class = '',
                min_delivery_days = 1,
                max_delivery_days = 1
            )
        else:
            return ShopShippingProfileDestination(
        )
        """

    def testShopShippingProfileDestination(self):
        """Test ShopShippingProfileDestination"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
