# coding: utf-8

# flake8: noqa
"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


# import models into model package
from etsy_python_sdk.models.buyer_taxonomy_node import BuyerTaxonomyNode
from etsy_python_sdk.models.buyer_taxonomy_node_properties import BuyerTaxonomyNodeProperties
from etsy_python_sdk.models.buyer_taxonomy_node_property import BuyerTaxonomyNodeProperty
from etsy_python_sdk.models.buyer_taxonomy_nodes import BuyerTaxonomyNodes
from etsy_python_sdk.models.buyer_taxonomy_property_scale import BuyerTaxonomyPropertyScale
from etsy_python_sdk.models.buyer_taxonomy_property_value import BuyerTaxonomyPropertyValue
from etsy_python_sdk.models.error_schema import ErrorSchema
from etsy_python_sdk.models.listing_image import ListingImage
from etsy_python_sdk.models.listing_images import ListingImages
from etsy_python_sdk.models.listing_inventory import ListingInventory
from etsy_python_sdk.models.listing_inventory_product import ListingInventoryProduct
from etsy_python_sdk.models.listing_inventory_product_offering import ListingInventoryProductOffering
from etsy_python_sdk.models.listing_inventory_with_associations import ListingInventoryWithAssociations
from etsy_python_sdk.models.listing_property_value import ListingPropertyValue
from etsy_python_sdk.models.listing_property_values import ListingPropertyValues
from etsy_python_sdk.models.listing_review import ListingReview
from etsy_python_sdk.models.listing_reviews import ListingReviews
from etsy_python_sdk.models.listing_translation import ListingTranslation
from etsy_python_sdk.models.listing_translations import ListingTranslations
from etsy_python_sdk.models.listing_variation_image import ListingVariationImage
from etsy_python_sdk.models.listing_variation_images import ListingVariationImages
from etsy_python_sdk.models.listing_video import ListingVideo
from etsy_python_sdk.models.listing_videos import ListingVideos
from etsy_python_sdk.models.model_self import ModelSelf
from etsy_python_sdk.models.money import Money
from etsy_python_sdk.models.payment import Payment
from etsy_python_sdk.models.payment_account_ledger_entries import PaymentAccountLedgerEntries
from etsy_python_sdk.models.payment_account_ledger_entry import PaymentAccountLedgerEntry
from etsy_python_sdk.models.payment_adjustment import PaymentAdjustment
from etsy_python_sdk.models.payment_adjustment_item import PaymentAdjustmentItem
from etsy_python_sdk.models.payments import Payments
from etsy_python_sdk.models.pong import Pong
from etsy_python_sdk.models.seller_taxonomy_node import SellerTaxonomyNode
from etsy_python_sdk.models.seller_taxonomy_nodes import SellerTaxonomyNodes
from etsy_python_sdk.models.shipping_carrier import ShippingCarrier
from etsy_python_sdk.models.shipping_carrier_mail_class import ShippingCarrierMailClass
from etsy_python_sdk.models.shipping_carriers import ShippingCarriers
from etsy_python_sdk.models.shop import Shop
from etsy_python_sdk.models.shop_holiday_preference import ShopHolidayPreference
from etsy_python_sdk.models.shop_listing import ShopListing
from etsy_python_sdk.models.shop_listing_file import ShopListingFile
from etsy_python_sdk.models.shop_listing_files import ShopListingFiles
from etsy_python_sdk.models.shop_listing_with_associations import ShopListingWithAssociations
from etsy_python_sdk.models.shop_listings import ShopListings
from etsy_python_sdk.models.shop_listings_with_associations import ShopListingsWithAssociations
from etsy_python_sdk.models.shop_production_partner import ShopProductionPartner
from etsy_python_sdk.models.shop_production_partners import ShopProductionPartners
from etsy_python_sdk.models.shop_receipt import ShopReceipt
from etsy_python_sdk.models.shop_receipt_shipment import ShopReceiptShipment
from etsy_python_sdk.models.shop_receipt_transaction import ShopReceiptTransaction
from etsy_python_sdk.models.shop_receipt_transactions import ShopReceiptTransactions
from etsy_python_sdk.models.shop_receipts import ShopReceipts
from etsy_python_sdk.models.shop_refund import ShopRefund
from etsy_python_sdk.models.shop_return_policies import ShopReturnPolicies
from etsy_python_sdk.models.shop_return_policy import ShopReturnPolicy
from etsy_python_sdk.models.shop_section import ShopSection
from etsy_python_sdk.models.shop_sections import ShopSections
from etsy_python_sdk.models.shop_shipping_profile import ShopShippingProfile
from etsy_python_sdk.models.shop_shipping_profile_destination import ShopShippingProfileDestination
from etsy_python_sdk.models.shop_shipping_profile_destinations import ShopShippingProfileDestinations
from etsy_python_sdk.models.shop_shipping_profile_upgrade import ShopShippingProfileUpgrade
from etsy_python_sdk.models.shop_shipping_profile_upgrades import ShopShippingProfileUpgrades
from etsy_python_sdk.models.shop_shipping_profiles import ShopShippingProfiles
from etsy_python_sdk.models.shops import Shops
from etsy_python_sdk.models.taxonomy_node_properties import TaxonomyNodeProperties
from etsy_python_sdk.models.taxonomy_node_property import TaxonomyNodeProperty
from etsy_python_sdk.models.taxonomy_property_scale import TaxonomyPropertyScale
from etsy_python_sdk.models.taxonomy_property_value import TaxonomyPropertyValue
from etsy_python_sdk.models.transaction_review import TransactionReview
from etsy_python_sdk.models.transaction_reviews import TransactionReviews
from etsy_python_sdk.models.transaction_variations import TransactionVariations
from etsy_python_sdk.models.type_discriminator import TypeDiscriminator
from etsy_python_sdk.models.update_listing_inventory_request import UpdateListingInventoryRequest
from etsy_python_sdk.models.update_listing_inventory_request_products_inner import UpdateListingInventoryRequestProductsInner
from etsy_python_sdk.models.update_listing_inventory_request_products_inner_offerings_inner import UpdateListingInventoryRequestProductsInnerOfferingsInner
from etsy_python_sdk.models.update_listing_inventory_request_products_inner_property_values_inner import UpdateListingInventoryRequestProductsInnerPropertyValuesInner
from etsy_python_sdk.models.update_variation_images_request import UpdateVariationImagesRequest
from etsy_python_sdk.models.update_variation_images_request_variation_images_inner import UpdateVariationImagesRequestVariationImagesInner
from etsy_python_sdk.models.user import User
from etsy_python_sdk.models.user_address import UserAddress
from etsy_python_sdk.models.user_addresses import UserAddresses
