# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class ShopListingFile(BaseModel):
    """
    A file associated with a digital listing.
    """ # noqa: E501
    listing_file_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The unique numeric ID of a file associated with a digital listing.")
    listing_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The numeric ID for the [listing](/documentation/reference#tag/ShopListing) associated to this transaction.")
    rank: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="The numeric index of the display order position of this file in the listing, starting at 1.")
    filename: Optional[StrictStr] = Field(default=None, description="The file name string for a file associated with a digital listing.")
    filesize: Optional[StrictStr] = Field(default=None, description="A human-readable format size string for the size of a file.")
    size_bytes: Optional[Annotated[int, Field(strict=True, ge=0)]] = Field(default=None, description="A number indicating the size of a file, measured in bytes.")
    filetype: Optional[StrictStr] = Field(default=None, description="A type string indicating a file's MIME type.")
    create_timestamp: Optional[Annotated[int, Field(strict=True, ge=946684800)]] = Field(default=None, description="The unique numeric ID of a file associated with a digital listing.")
    created_timestamp: Optional[Annotated[int, Field(strict=True, ge=946684800)]] = Field(default=None, description="The unique numeric ID of a file associated with a digital listing.")
    __properties: ClassVar[List[str]] = ["listing_file_id", "listing_id", "rank", "filename", "filesize", "size_bytes", "filetype", "create_timestamp", "created_timestamp"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of ShopListingFile from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of ShopListingFile from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "listing_file_id": obj.get("listing_file_id"),
            "listing_id": obj.get("listing_id"),
            "rank": obj.get("rank"),
            "filename": obj.get("filename"),
            "filesize": obj.get("filesize"),
            "size_bytes": obj.get("size_bytes"),
            "filetype": obj.get("filetype"),
            "create_timestamp": obj.get("create_timestamp"),
            "created_timestamp": obj.get("created_timestamp")
        })
        return _obj


