# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictInt, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from etsy_python_sdk.models.taxonomy_property_scale import TaxonomyPropertyScale
from etsy_python_sdk.models.taxonomy_property_value import TaxonomyPropertyValue
from typing import Optional, Set
from typing_extensions import Self

class TaxonomyNodeProperty(BaseModel):
    """
    A product property definition.
    """ # noqa: E501
    property_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The unique numeric ID of this product property.")
    name: Optional[StrictStr] = Field(default=None, description="The name string for this taxonomy node.")
    display_name: Optional[StrictStr] = Field(default=None, description="The human-readable product property name string.")
    scales: Optional[List[TaxonomyPropertyScale]] = Field(default=None, description="A list of available scales.")
    is_required: Optional[StrictBool] = Field(default=None, description="When true, listings assigned eligible taxonomy IDs require this property.")
    supports_attributes: Optional[StrictBool] = Field(default=None, description="When true, you can use this property in listing attributes.")
    supports_variations: Optional[StrictBool] = Field(default=None, description="When true, you can use this property in listing variations.")
    is_multivalued: Optional[StrictBool] = Field(default=None, description="When true, you can assign multiple property values to this property")
    max_values_allowed: Optional[StrictInt] = Field(default=None, description="When true, you can assign multiple property values to this property")
    possible_values: Optional[List[TaxonomyPropertyValue]] = Field(default=None, description="A list of supported property value strings for this property.")
    selected_values: Optional[List[TaxonomyPropertyValue]] = Field(default=None, description="A list of property value strings automatically and always selected for the given property.")
    __properties: ClassVar[List[str]] = ["property_id", "name", "display_name", "scales", "is_required", "supports_attributes", "supports_variations", "is_multivalued", "max_values_allowed", "possible_values", "selected_values"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of TaxonomyNodeProperty from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # override the default output from pydantic by calling `to_dict()` of each item in scales (list)
        _items = []
        if self.scales:
            for _item_scales in self.scales:
                if _item_scales:
                    _items.append(_item_scales.to_dict())
            _dict['scales'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in possible_values (list)
        _items = []
        if self.possible_values:
            for _item_possible_values in self.possible_values:
                if _item_possible_values:
                    _items.append(_item_possible_values.to_dict())
            _dict['possible_values'] = _items
        # override the default output from pydantic by calling `to_dict()` of each item in selected_values (list)
        _items = []
        if self.selected_values:
            for _item_selected_values in self.selected_values:
                if _item_selected_values:
                    _items.append(_item_selected_values.to_dict())
            _dict['selected_values'] = _items
        # set to None if max_values_allowed (nullable) is None
        # and model_fields_set contains the field
        if self.max_values_allowed is None and "max_values_allowed" in self.model_fields_set:
            _dict['max_values_allowed'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of TaxonomyNodeProperty from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "property_id": obj.get("property_id"),
            "name": obj.get("name"),
            "display_name": obj.get("display_name"),
            "scales": [TaxonomyPropertyScale.from_dict(_item) for _item in obj["scales"]] if obj.get("scales") is not None else None,
            "is_required": obj.get("is_required"),
            "supports_attributes": obj.get("supports_attributes"),
            "supports_variations": obj.get("supports_variations"),
            "is_multivalued": obj.get("is_multivalued"),
            "max_values_allowed": obj.get("max_values_allowed"),
            "possible_values": [TaxonomyPropertyValue.from_dict(_item) for _item in obj["possible_values"]] if obj.get("possible_values") is not None else None,
            "selected_values": [TaxonomyPropertyValue.from_dict(_item) for _item in obj["selected_values"]] if obj.get("selected_values") is not None else None
        })
        return _obj


