# coding: utf-8

"""
    Etsy Open API v3

    <div class=\"wt-text-body-01\"><p class=\"wt-pt-xs-2 wt-pb-xs-2\">Etsy's Open API provides a simple RESTful interface for various Etsy.com features. The API endpoints are meant to replace Etsy's Open API v2, which is scheduled to end service in 2022.</p><p class=\"wt-pb-xs-2\">All of the endpoints are callable and the majority of the API endpoints are now in a beta phase. This means we do not expect to make any breaking changes before our general release. A handful of endpoints are currently interface stubs (labeled “Feedback Only”) and returns a \"501 Not Implemented\" response code when called.</p><p class=\"wt-pb-xs-2\">If you'd like to report an issue or provide feedback on the API design, <a target=\"_blank\" class=\"wt-text-link wt-p-xs-0\" href=\"https://github.com/etsy/open-api/discussions\">please add an issue in Github</a>.</p></div>&copy; 2021-2025 Etsy, Inc. All Rights Reserved. Use of this code is subject to Etsy's <a class='wt-text-link wt-p-xs-0' target='_blank' href='https://www.etsy.com/legal/api'>API Developer Terms of Use</a>.

    The version of the OpenAPI document: 3.0.0
    Contact: developers@etsy.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import pprint
import re  # noqa: F401
import json

from pydantic import BaseModel, ConfigDict, Field, StrictBool, StrictStr
from typing import Any, ClassVar, Dict, List, Optional
from typing_extensions import Annotated
from typing import Optional, Set
from typing_extensions import Self

class UserAddress(BaseModel):
    """
    Represents a user's address.
    """ # noqa: E501
    user_address_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The numeric ID of the user's address.")
    user_id: Optional[Annotated[int, Field(strict=True, ge=1)]] = Field(default=None, description="The user's numeric ID.")
    name: Optional[StrictStr] = Field(default=None, description="The user's name for this address.")
    first_line: Optional[StrictStr] = Field(default=None, description="The first line of the user's address.")
    second_line: Optional[StrictStr] = Field(default=None, description="The second line of the user's address.")
    city: Optional[StrictStr] = Field(default=None, description="The city field of the user's address.")
    state: Optional[StrictStr] = Field(default=None, description="The state field of the user's address.")
    zip: Optional[StrictStr] = Field(default=None, description="The zip code field of the user's address.")
    iso_country_code: Optional[StrictStr] = Field(default=None, description="The ISO code of the country in this address.")
    country_name: Optional[StrictStr] = Field(default=None, description="The name of the user's country.")
    is_default_shipping_address: Optional[StrictBool] = Field(default=None, description="Is this the user's default shipping address.")
    __properties: ClassVar[List[str]] = ["user_address_id", "user_id", "name", "first_line", "second_line", "city", "state", "zip", "iso_country_code", "country_name", "is_default_shipping_address"]

    model_config = ConfigDict(
        populate_by_name=True,
        validate_assignment=True,
        protected_namespaces=(),
    )


    def to_str(self) -> str:
        """Returns the string representation of the model using alias"""
        return pprint.pformat(self.model_dump(by_alias=True))

    def to_json(self) -> str:
        """Returns the JSON representation of the model using alias"""
        # TODO: pydantic v2: use .model_dump_json(by_alias=True, exclude_unset=True) instead
        return json.dumps(self.to_dict())

    @classmethod
    def from_json(cls, json_str: str) -> Optional[Self]:
        """Create an instance of UserAddress from a JSON string"""
        return cls.from_dict(json.loads(json_str))

    def to_dict(self) -> Dict[str, Any]:
        """Return the dictionary representation of the model using alias.

        This has the following differences from calling pydantic's
        `self.model_dump(by_alias=True)`:

        * `None` is only added to the output dict for nullable fields that
          were set at model initialization. Other fields with value `None`
          are ignored.
        """
        excluded_fields: Set[str] = set([
        ])

        _dict = self.model_dump(
            by_alias=True,
            exclude=excluded_fields,
            exclude_none=True,
        )
        # set to None if second_line (nullable) is None
        # and model_fields_set contains the field
        if self.second_line is None and "second_line" in self.model_fields_set:
            _dict['second_line'] = None

        # set to None if state (nullable) is None
        # and model_fields_set contains the field
        if self.state is None and "state" in self.model_fields_set:
            _dict['state'] = None

        # set to None if zip (nullable) is None
        # and model_fields_set contains the field
        if self.zip is None and "zip" in self.model_fields_set:
            _dict['zip'] = None

        # set to None if iso_country_code (nullable) is None
        # and model_fields_set contains the field
        if self.iso_country_code is None and "iso_country_code" in self.model_fields_set:
            _dict['iso_country_code'] = None

        # set to None if country_name (nullable) is None
        # and model_fields_set contains the field
        if self.country_name is None and "country_name" in self.model_fields_set:
            _dict['country_name'] = None

        return _dict

    @classmethod
    def from_dict(cls, obj: Optional[Dict[str, Any]]) -> Optional[Self]:
        """Create an instance of UserAddress from a dict"""
        if obj is None:
            return None

        if not isinstance(obj, dict):
            return cls.model_validate(obj)

        _obj = cls.model_validate({
            "user_address_id": obj.get("user_address_id"),
            "user_id": obj.get("user_id"),
            "name": obj.get("name"),
            "first_line": obj.get("first_line"),
            "second_line": obj.get("second_line"),
            "city": obj.get("city"),
            "state": obj.get("state"),
            "zip": obj.get("zip"),
            "iso_country_code": obj.get("iso_country_code"),
            "country_name": obj.get("country_name"),
            "is_default_shipping_address": obj.get("is_default_shipping_address")
        })
        return _obj


