name: Regenerate SDK

on:
  workflow_dispatch:

permissions:
  contents: write  # Allow writing to the repository for committing changes
  pull-requests: write  # Allow writing to pull requests for creating PRs

jobs:
  generate-sdk:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Poetry
        run: pip install poetry

      - name: Install dependencies
        run: make install

      - name: Clean existing SDK
        run: make clean

      - name: Generate SDK
        run: make generate

      - name: Run tests
        run: make test

      - name: Set environment variables
        run: |
          export TAG_TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')
          echo "TAG_TIMESTAMP=$TAG_TIMESTAMP" >> $GITHUB_ENV
          echo "$TAG_TIMESTAMP" > VERSION

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        env:
          GITHUB_TOKEN: ${{ secrets.ETSY_SDK_GITHUB_TOKEN }}
        with:
          title: "chore: regenerate SDK from latest OpenAPI spec (${{ env.TAG_TIMESTAMP }})"
          body: "This PR regenerates the SDK using the latest OpenAPI spec."
          base: main
          branch: "chore/regenerate-sdk-${{ env.TAG_TIMESTAMP }}"
          add-paths: |
              src/
              openapi/etsy-openapi.json
              VERSION
          commit-message: "chore: regenerate SDK from latest OpenAPI spec (${{ env.TAG_TIMESTAMP }})"
          reviewers: weirdion
          delete-branch: true
