name: Tag Generated SDK

on:
  push:
    branches:
      - main

permissions:
  contents: write  # Allow writing to the repository for tagging
  pull-requests: write  # Allow writing to pull requests for tagging
  metadata: read  # Allow reading metadata for the repository

jobs:
  tag-generate-sdk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensure full history is fetched for tagging

      - name: On PR merge, tag the generated SDK
        env:
          GITHUB_TOKEN: ${{ secrets.ETSY_SDK_GITHUB_TOKEN }}
        run: |
          export TAG_DATE=$(date +'%Y-%m-%d')
          export TAG_TIMESTAMP=$(date +'%Y-%m-%d-%H%M%S')
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          echo "Fetching tags from remote repository..."
          git fetch --tags https://x-access-token:${GITHUB_TOKEN}@github.com/weirdion/etsy-python-sdk.git
          git tag -a $TAG_TIMESTAMP -m "Generated SDK on $TAG_TIMESTAMP"
          git tag -a -f $TAG_DATE -m "Generated SDK on $TAG_DATE"
          echo "Pushing tags to remote repository..."
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/weirdion/etsy-python-sdk.git $TAG_TIMESTAMP
          git push https://x-access-token:${GITHUB_TOKEN}@github.com/weirdion/etsy-python-sdk.git -f $TAG_DATE
